name: PenChecker
version: '1.0-SNAPSHOT'
main: pl.masnypen.penChecker.Main
api-version: '1.20'
author: MasnyPen
description: Plugin na sprawdzanie graczy.

commands:
  ustawsprawdzania:
    description: Ustaw lokację, gdzie gracze będą sprawdzani.
    permission: penchecker.admin
    permission-message: "&cNie masz uprawnień do ustawienia lokacji sprawdzania!"

  sprawdz:
    description: Rozpocznij sprawdzanie danego gracza.
    permission: penchecker.use
    permission-message: "&cNie masz uprawnień do sprawdzania graczy!"

  czysty:
    description: Oznacz sprawdzanego gracza jako czystego.
    permission: penchecker.use
    permission-message: "&cNie masz uprawnień, aby oznaczyć gracza jako czystego!"

  skazany:
    description: Oznacz gracza jako winnego (cheatera).
    permission: penchecker.use
    permission-message: "&cNie masz uprawnień, aby oznaczyć gracza jako skazanego!"
  penchecker:
    description: Ogolna komenda pencheckera.
    permission-message: "&cNie masz uprawnień, aby oznaczyć gracza jako skazanego!"


permissions:
  penchecker.admin:
    description: Uprawnienia administracyjne do zarządzania spawnem i konfiguracją.
    default: op

  penchecker.use:
    description: Uprawnienia do wykonywania podstawowych komend sprawdzania.
    default: op
