name: PenChecker
version: '1.0'
main: pl.masnypen.penChecker.Main
api-version: '1.13'
author: MasnyPen
description: Plugin na sprawdzanie graczy.

commands:
  setchecklocation:
    description: Set the location where players will be checked.
    permission: penchecker.admin
    permission-message: "You do not have permission to use this command!"

  startcheck:
    description: Start checking a specific player.
    permission: penchecker.use
    permission-message: "You do not have permission to use this command!"

  markclean:
    description: Mark the checked player as clean.
    permission: penchecker.use
    permission-message: "You do not have permission to use this command!"

  markguilty:
    description: Mark the player as guilty (cheater).
    permission: penchecker.use
    permission-message: "You do not have permission to use this command!"

  penchecker:
    description: General PenChecker command.
    permission-message: "You do not have permission to use this command!"


permissions:
  penchecker.admin:
    description: Administrative permissions for managing the checking location and configuration.
    default: op

  penchecker.use:
    description: Permissions to execute basic checking commands.
    default: op
