name: PenChecker
version: '1.0-SNAPSHOT'
main: pl.masnypen.penChecker.Main
api-version: '1.20'
authors: [ MasnyPen ]
description: Plugin na sprawdzanie

commands:
  ustawspawnsprawdzania:
    description: Ustaw lokacje sprawdzania
  sprawdz:
    description: Sprawdz Gracza
  czysty:
    description: Sprawdzanie czysty
  skazany:
    description: tego typu benc
