name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          java-package: 'jdk'
          distribution: 'zulu'
          check-latest: false

      - name: Build with Maven
        run: mvn package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PenChecker
          path: target/*.jar
